package messaging;

public enum MessageType {

    REGISTRATION_REQUEST,
    REGISTRATION_RESPONSE,

    LOGIN_REQUEST,
    LOGIN_RESPONSE,

    LOGOUT_REQUEST,
    LOGOUT_RESPONSE,

    INFORM_REQUEST,
    INFORM_RESPONSE,

    LIST_REQUEST,
    LIST_RESPONSE,

    DETAILS_REQUEST,
    DETAILS_RESPONSE,

    NOTIFY_REQUEST,
    NOTIFY_RESPONSE,

    CHECK_ACTIVE_REQUEST,
    CHECK_ACTIVE_RESPONSE,
    
    SIMPLE_DOWNLOAD_REQUEST,
    SIMPLE_DOWNLOAD_RESPONSE,

    ERROR_RESPONSE
}